### ISSUE TITLE
matches should still return an Iterator when no match is found

### ISSUE THREAD

**Issue by filipeom** [ChrisTimperley/comby-python#29]
I'm trying to rewrite a bunch of code, however a few source files will not match the pattern and `matches` simply explodes on `jsn = json.loads(self.call(cmd_s, text=source))` because `call` returns `None`. Is this the expected behaviour? To bypass this I'm catching the `JSONDecodeError` and going to the next file, but it would be nice if  we simply had an empty Iterator

**Comment by ChrisTimperley** [comment]
That's surprising. I wouldn't have expected `p.stdout.decode('utf-8')` to be able to return `None`. Thanks for reporting it. I agree that `matches` should still return an `Iterator` when a match isn't found.

Just to double check, what version of `comby-python` are you using? Also, would you mind sharing some text that reproduces the issue?

**Comment by ChrisTimperley** [comment]
A possible workaround is to add a keyword argument `suppress_errors: bool = True` to `matches` that allows `JSONDecodeError` to be caught (and maybe writes a warning to the logger).

**Comment by filipeom** [comment]
I'm running `python-comby 0.0.2` with `comby binary 1.0.0`
```python
>>> from comby import Comby
>>> comby = Comby()
>>> source = 'a[i] = a[i] + 1'
>>> match = ':[[var]] ='
>>> replace = ':[var]_:[id()] ='
>>> list(comby.matches(source, match))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/filipe/.local/lib/python3.9/site-packages/comby/binary.py", line 106, in matches
    jsn = json.loads(self.call(cmd_s, text=source))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I'm also going to update comby to see if the error persists over the updated version. For my use case I think that workaround would also work!

**Comment by jrfaller** [comment]
I also got this bug, with lib 0.02 and bin 1.6.0 on Mac OS X.

```python
from comby import Comby

comby = Comby()
match = 'foo'
source= 'bar'
match = list(comby.matches(source, match))
print(match)
```

leads to:

```shell
Traceback (most recent call last):
  File "/Users/falleri/work/code/nbshowcase/./test_comby.py", line 8, in <module>
    match = list(comby.matches(source, match))
  File "/usr/local/lib/python3.9/site-packages/comby/binary.py", line 106, in matches
    jsn = json.loads(self.call(cmd_s, text=source))
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Could you tell me how to apply the workaround advised above?

Cheers!

**Comment by jrfaller** [comment]
Apparently modifying the end of the `matches` function in `binary.py` as such works :

```python
        jsn = json.loads(self.call(cmd_s, text=source) or 'null')
        if jsn is not None:
            jsn = jsn['matches']
            for jsn_match in jsn:
                yield Match.from_dict(jsn_match)
```

Do you think it make sense? I can supply a pull-request if you want.

**Comment by ChrisTimperley** [comment]
> Apparently modifying the end of the `matches` function in `binary.py` as such works :
> 
> ```python
>         jsn = json.loads(self.call(cmd_s, text=source) or 'null')
>         if jsn is not None:
>             jsn = jsn['matches']
>             for jsn_match in jsn:
>                 yield Match.from_dict(jsn_match)
> ```
> 
> Do you think it make sense? I can supply a pull-request if you want.

That makes sense. It would be great if you could submit a PR. Thanks!

**Comment by jrfaller** [comment]
It's done, I have also added a test case to avoid any regression in the future.

Cheers!
